GET http://localhost:4000/

###

POST http://localhost:4000/user/register HTTP/1.1
content-type: application/json

{
    "username": "test1",
    "email": "test1@gmail.com",
    "password": "catcat"
}

###

POST http://localhost:4000/user/signin HTTP/1.1
content-type: application/json

{
    "identifier": "test1",
    "password": "catcat"
}